import 'models/listing.dart';

class DummyData {
  static List<Listing> dummyListings = [
    Listing(
      id: '1',
      foodName: 'sminoff ice',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 2,
      itemPrice: 120,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '2',
      foodName: 'savanah',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 170,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '3',
      foodName: 'guiness',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 3,
      itemPrice: 90,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '4',
      foodName: 'club (big)',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 15,
      itemPrice: 60,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '5',
      foodName: 'club(mini)',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 10,
      itemPrice: 90,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '6',
      foodName: 'eagle',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 60,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '7',
      foodName: 'gulder',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 60,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '8',
      foodName: 'club shady',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 2,
      itemPrice: 50,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '9',
      foodName: 'kiss',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 170,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '10',
      foodName: 'hunters',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 170,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '11',
      foodName: 'henniken (bottle)',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 2,
      itemPrice: 170,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '12',
      foodName: 'fox',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 140,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '13',
      foodName: 'panache',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 65,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '14',
      foodName: 'cocktail can',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 86,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '15',
      foodName: 'malt plastic bott',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 3,
      itemPrice: 38,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '16',
      foodName: 'malt can',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 90,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '17',
      foodName: 'mineral (can)',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 3,
      itemPrice: 78,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '18',
      foodName: 'pepsi bottle',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 2,
      itemPrice: 28,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '19',
      foodName: 'don simon',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 100,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '20',
      foodName: 'series',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 130,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '21',
      foodName: 'vitamilk',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 104,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '22',
      foodName: 'welch',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 4,
      itemPrice: 120,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '23',
      foodName: 'rush energy drink',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 21,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '24',
      foodName: '5 star energy drink',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 21,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '25',
      foodName: 'storm energy drink (big)',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 34,
      addedStock: 1000,
      openingStock: 0,
    ),
    Listing(
      id: '26',
      foodName: 'red bull',
      time: DateTime.now().subtract(Duration(days: 1)),
      quantitySold: 1,
      itemPrice: 180,
      addedStock: 1000,
      openingStock: 0,
    ),
  ];
}
